In [1]:
import pandas as pd

df = pd.read_csv('customer_shopping_behavior (1)-Copy1.csv')

# Remove all unnamed / hidden columns
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

#  Strip spaces from column names
df.columns = df.columns.str.strip()

#  Remove fully empty columns 
df = df.dropna(axis=1, how='all')

# Save clean file
df.to_csv('cleaned_customer_data.csv', index=False)

print(df.columns)

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [3]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [4]:
df.describe(include= 'all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [5]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [6]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [7]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [2]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns = {'purchase_amount_(usd)':'purchase_amount'})

In [3]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [4]:
# Create a age_group column

labels = ['Young Adult','Adult','Middle-Aged','Senior']
df['age_group'] = pd.qcut(df['age'] ,q=4,labels=labels)

In [5]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-Aged
1   19  Young Adult
2   50  Middle-Aged
3   21  Young Adult
4   45  Middle-Aged
5   46  Middle-Aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-Aged

In [ ]:
# Create a column purchase_frequency_days

In [23]:
frequency_mapping = {
    'Fortnightly':14,
    'Weekly' : 7,
    'monthly':30,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Annually':365,
    'every 3 months': 90
}

df['Purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [24]:
df[['Purchase_frequency_days','frequency_of_purchases']].head(10)

   Purchase_frequency_days frequency_of_purchases
0                     14.0            Fortnightly
1                     14.0            Fortnightly
2                      7.0                 Weekly
3                      7.0                 Weekly
4                    365.0               Annually
5                      7.0                 Weekly
6                     90.0              Quarterly
7                      7.0                 Weekly
8                    365.0               Annually
9                     90.0              Quarterly

In [28]:
(df['discount_applied'] == df['promo_code_used']).all()

KeyError: 'promo_code_used'

In [6]:
df = df.drop('promo_code_used',axis=1)

In [7]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group'],
      dtype='object')

In [8]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\dell\anaconda3\lib\site-packages (9.7.0)
Note: you may need to restart the kernel to use updated packages.

In [9]:
!pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\dell\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: pymysql in c:\users\dell\anaconda3\lib\site-packages (1.1.2)
Requirement already satisfied: greenlet>=1 in c:\users\dell\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\dell\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)

In [10]:
# connecting to database
import mysql.connector

conn = mysql.connector.connect(
    host = "localhost",
    user = "root",
    password = "root",
    database = "customer_shopping_behavior"
)

print("connected successfully")

from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:root@localhost/customer_shopping_behavior")

# loading dataframe into database
df.to_sql(
    name='customer_data',   # table name
    con=engine,
    if_exists='replace',    # replace if exists
    index=False,
)

# Readback from mysql

query = "SELECT * FROM customer_data"
df_sql = pd.read_sql(query, engine)

df_sql.head()

connected successfully

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-Aged
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-Aged
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-Aged

In [11]:
df.to_csv('cleaned_customer_data.csv', index=False, encoding='utf-8')

In [12]:
df.describe

<bound method NDFrame.describe of       customer_id  age  gender item_purchased     category  purchase_amount  \
0               1   55    Male         Blouse     Clothing               53
1               2   19    Male        Sweater     Clothing               64
2               3   50    Male          Jeans     Clothing               73
3               4   21    Male        Sandals     Footwear               90
4               5   45    Male         Blouse     Clothing               49
...           ...  ...     ...            ...          ...              ...
3895         3896   40  Female         Hoodie     Clothing               28
3896         3897   52  Female       Backpack  Accessories               49
3897         3898   46  Female           Belt  Accessories               33
3898         3899   44  Female          Shoes     Footwear               77
3899         3900   52  Female        Handbag  Accessories               81

           location size      color  season  review_rating  \
0          Kentucky    L       Gray  Winter            3.1
1             Maine    L     Maroon  Winter            3.1
2     Massachusetts    S     Maroon  Spring            3.1
3      Rhode Island    M     Maroon  Spring            3.5
4            Oregon    M  Turquoise  Spring            2.7
...             ...  ...        ...     ...            ...
3895       Virginia    L  Turquoise  Summer            4.2
3896           Iowa    L      White  Spring            4.5
3897     New Jersey    L      Green  Spring            2.9
3898      Minnesota    S      Brown  Summer            3.8
3899     California    M      Beige  Spring            3.1

     subscription_status   shipping_type discount_applied  previous_purchases  \
0                    Yes         Express              Yes                  14
1                    Yes         Express              Yes                   2
2                    Yes   Free Shipping              Yes                  23
3                    Yes    Next Day Air              Yes                  49
4                    Yes   Free Shipping              Yes                  31
...                  ...             ...              ...                 ...
3895                  No  2-Day Shipping               No                  32
3896                  No    Store Pickup               No                  41
3897                  No        Standard               No                  24
3898                  No         Express               No                  24
3899                  No    Store Pickup               No                  33

     payment_method frequency_of_purchases    age_group
0             Venmo            Fortnightly  Middle-Aged
1              Cash            Fortnightly  Young Adult
2       Credit Card                 Weekly  Middle-Aged
3            PayPal                 Weekly  Young Adult
4            PayPal               Annually  Middle-Aged
...             ...                    ...          ...
3895          Venmo                 Weekly        Adult
3896  Bank Transfer              Bi-Weekly  Middle-Aged
3897          Venmo              Quarterly  Middle-Aged
3898          Venmo                 Weekly        Adult
3899          Venmo              Quarterly  Middle-Aged

[3900 rows x 18 columns]>